[package]
name = "backend"
version = "1.0.53"
edition = "2021"

[[bin]]
name = "algorithm"
path = "src/main.rs"

[lib]
name = "vnscope"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
sharding = [
	"default",
	"sea-query",
]
proxy = [
	"redis",
	"infisical",
]
python = ["pyo3", "pyo3-asyncio", "pyo3-polars", "polars"]
bff = [
	"default"
]
crawl = [
	"default",
]
default = [
	"airtable-api",
	"redis",
	"actix-web",
	"async-graphql",
	"async-graphql-actix-web",
	"actix-web-prometheus",
	"sea-orm",
	"sea-query",
	"quick-xml",
	"hmac",
	"hex",
	"sha2",
	"infisical",
	"clap",
	"clap_derive",
]

[dependencies]
# Data modeling
async-graphql = { version = "7", optional = true }
async-graphql-actix-web = { version = "7", optional = true }
serde = "1.0.123"
serde_json = "1.0.44"
parquet = "53"
arrow = "53"
anyhow = "1.0"
polars = { version = "0.36.2", features = ["parquet", "lazy"], optional = true }

# Python bindings
pyo3 = { version = "0.20", features = ["extension-module"], optional = true }
pyo3-asyncio = { version = "0.20.0", optional = true }
pyo3-polars = { version = "0.10.0", optional = true }

# Algorithm for generic
rand_distr = "0.4.3"
statrs = "0.16.0"
rand = "0.8.5"
rayon = "1.10.0"
itertools = "0.13" # @TODO: use one version of itertools
nalgebra = "0.34.1"
influxdb = { version = "0.7.2", features = ["derive"] }

# feature order management
airtable-api = { version = "0.1", optional = true } # @TODO: remove airtable

# feature dashboard monitoring
actix-web-prometheus = { version = "0.1.2", optional = true }
prometheus = "0.13.3"

# Crawling data in background
reqwest = { version = "0.11.27", default-features = false, features = ["json", "blocking", "rustls-tls"] }
reqwest-retry = "0.4.0"
reqwest-middleware = "0.2.5"
cron-parser = "0.8.1"
actix-rt = "2.10.0"
actix = "0.13.5"
awc = "3.5.1"
bytes = "1.10.1"
tungstenite = { version = "0.28.0", features = ["native-tls"] }
tokio = { version = "1.26.0", features = ["full"] }
aws-sdk-s3 = { version = "1.90.0", default-features = false, features = ["rustls", "default-https-client", "rt-tokio"] }
aws-config = { version = "1.6.3", default-features = false, features = ["rustls", "default-https-client", "rt-tokio"] }
sea-orm = { version = "1.1.14", optional = true, features = ["debug-print", "runtime-tokio-rustls", "sqlx-mysql"] }
sea-query = { version = "0.32.7", optional = true }

# Common
lazy_static = "1.5.0"
chrono-tz = "0.9.0"
chrono = "= 0.4.39"
futures = "0.3"
log = "0.4.22"
clap = { version = "4.5.47", optional = true, features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1", optional = true }

# Web application
dotenvy = "0.15.7"
futures-util = "0.3"
infisical = { version = "0.0.3", optional = true }
hmac = { version = "0.12", optional = true }
hex = { version = "0.4.3", optional = true }
sha2 = { version = "0.10", optional = true }
quick-xml = { version = "0.31", optional = true }
actix-web = { version = "4.3.1", optional = true }
redis = { version = "0.32.5", optional = true, features = ["aio", "tokio-comp"] }
env_logger = { version = "0.8.2" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio = { version = "1.26.0", features = ["full", "test-util"] }
candle-core = { version = "0.9.1" }
candle-nn = { version = "0.9.1" }
candle-transformers = { version = "0.9.1" }
hf-hub = { version = "0.3" }
tokenizers = { version = "0.21.4" }
rstest = "0.18"

[package.metadata.deb]
maintainer = "Hung Pham <hung0913208@gmail.com>"
priority = "optional"
section = "utils"
assets = [
    ["target/release/algorithm", "usr/bin/bff", "755"],
    ["../../conf/bff.service", "lib/systemd/system/", "644"]
]
maintainer-scripts = "debian/"

[profile.dev]
debug = 0
opt-level = 0

[profile.release]
opt-level = 3          # tối ưu tốc độ (O3)
lto = "fat"            # link-time optimization đầy đủ
codegen-units = 1      # compile 1 unit -> tối ưu tốt hơn
panic = "abort"        # không cần stack unwinding, giảm size
strip = true           # bỏ debug symbols (Rust >= 1.73)
