[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[features]
portal  = ["default"]
cms     = ["default"]
default = []

[dependencies]
# Error handler
anyhow = "1.0"

# Tracking
gtag-js = "0.2"

# Log
console_error_panic_hook = "0.1"
console_log = "0.2"
log = "0.4"

# Web platform
gloo-events = "0.1"
wasm-bindgen = "0.2"
leptos = { version = "0.8.8", features = ["csr"] }
leptos_router = { version = "0.8.8" }
web-sys = { version = "0.3.77", features = ["Window", "Event", "Screen", "OrientationType", "ScreenOrientation"] }

# Data modeling and handler
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }

[profile.release]
opt-level = 3
